CricketManagementAppMVC/CricketWebMVC/Models/Cricketer.cs
namespace CricketWebMVC.Models
{
    public class Cricketer
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public int JersyNo {  get; set; }

        public int Ranker { get; set; }

        public int Age { get; set; }    

        public DateTime DOJ { get; set; }

        public string Role { get; set; }
    }
}

CricketManagementAppMVC/CricketWebMVC/Models/ErrorViewModel.cs
namespace CricketWebMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CricketManagementAppMVC/CricketWebMVC/Controllers/CricketerController.cs
using CricketWebMVC.Models;
using CricketWebMVC.Services;
using Microsoft.AspNetCore.Mvc;

namespace CricketWebMVC.Controllers
{
    public class CricketerController : Controller
    {      private readonly ICricketerService _cricketerService;

        public CricketerController(ICricketerService cricketerService)
        {
            _cricketerService = cricketerService;   
        }
        

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetAllCricketer()
        {
       
            return View(_cricketerService.GetAllCricketer());
        }

        public IActionResult AddCricketer()
        {
            return View();
        }

        [HttpPost]

        public IActionResult AddCricketer(Cricketer cricketer)
        {   
             _cricketerService.AddCricketer(cricketer);
            return View(cricketer);
        }
        public IActionResult DeleteCricketer()
        {
            return View();
        }
        [HttpPost]
        public IActionResult DeleteCricketer(int Id)
        { 
            _cricketerService.DeleteCricketer(Id);

            return View();
        }
        public IActionResult UpdateCricketer()
        {
            return View();
        }

        [HttpPost]
        public IActionResult UpdateCricketer(Cricketer cricketer)
        {
            _cricketerService.UpdateCricketer(cricketer);
            return View();
        }

        

        [HttpGet]
        public IActionResult SortByRole()
        {

            
            return View(_cricketerService.SortByRole());
        }
        public IActionResult SearchByRole()
        {
            return View();
        }


        [HttpPost]
        public IActionResult SearchByRole(string role)
        {
            return Json(_cricketerService.SearchByRole(role));  
        }


    }
}

CricketManagementAppMVC/CricketWebMVC/Controllers/HomeController.cs
using CricketWebMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CricketWebMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CricketManagementAppMVC/CricketWebMVC/Views/Cricketer/AddCricketer.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Add New Cricketer</h1>

<form action="AddCricketer" method="post">
    <div>
        Id:<input type="text" id="Id" name="Id" /><br />
        Name:<input type="text" id="Name" name="Name" /><br />
        JersyNo:<input type="text" id="JersyNo" name="JersyNo" /><br />
        Ranker:<input type="text" id="Ranker" name="Ranker" /><br />

        Age:<input type="text" id="Age" name="Age" /> <br />
        DOJ:<input type="date" id="DOJ" name="DOJ" /><br />
        Role:<input type="text" id="Role" name="Role" /><br />
    </div>
    <button type="submit" id="btn" name="btn">Add New Cricketer</button>
</form>

CricketManagementAppMVC/CricketWebMVC/Views/Cricketer/DeleteCricketer.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Delete Cricketer</h1>

<form action="DeleteCricketer" method="post">
    <div>
        Id:<input type="text" id="Id" name="Id" /><br />
        </div>

    <button type="submit" id="btn" name="btn">Delete  Cricketer</button>
</form>

CricketManagementAppMVC/CricketWebMVC/Views/Cricketer/GetAllCricketer.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}
<h1> All Cricketer List</h1>

<list>
    <ul>
        @foreach(var cricketer in Model){
       <div>
            <li>
              
                  Id: @cricketer.Id;
                  Name: @cricketer.Name;
                  JersyNo: @cricketer.JersyNo;
                  Ranker: @cricketer.Ranker;
                  Age: @cricketer.Age;

                  DOJ: @cricketer.DOJ;
                  Role:@cricketer.Role;
            </li>
           </div>
     
        }
    </ul>
</list>

CricketManagementAppMVC/CricketWebMVC/Views/Cricketer/SearchByRole.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Search Cricketer</h1>

<form action="SearchByRole" method="post">
    <div>
        Role:<input type="text" id="Role" name="Role" /><br />
</div>
    <button type="submit" id="btn" name="btn">Search</button>
    </form>

CricketManagementAppMVC/CricketWebMVC/Views/Cricketer/SortByRole.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}
<h1> Sorted Cricketer List</h1>

<list>
    <ul>
        @foreach (var cricketer in Model)
        {
            <div>
            <li>

                Id: @cricketer.Id;
                Name: @cricketer.Id;
                JersyNo: @cricketer.JersyNo;
                Ranker: @cricketer.Ranker;
                Age: @cricketer.Age;

                DOJ: @cricketer.DOJ;
                Role:@cricketer.Role;
            </li>
            </div>

        }
    </ul>
</list>

CricketManagementAppMVC/CricketWebMVC/Views/Cricketer/UpdateCricketer.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Update Cricketer</h1>

<form action="UpdateCricketer" method="post">
    <div>
        Id:<input type="text" id="Id" name="Id" /><br />
        Ranker:<input type="text" id="Ranker" name="Ranker" /><br />

        Age:<input type="text" id="Age" name="Age" /> <br />

        </div>

    <button type="submit" id="btn" name="btn">Update Cricketer</button>
</form>

CricketManagementAppMVC/CricketWebMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CricketManagementAppMVC/CricketWebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CricketWebMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CricketWebMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CricketWebMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cricketer" asp-action="AddCricketer">Add Cricketer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cricketer" asp-action="DeleteCricketer">Delete Cricketer</a>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cricketer" asp-action="UpdateCricketer">Update Cricketer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cricketer" asp-action="SortByRole">Sorting Cricketer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cricketer" asp-action="SearchByRole">Search Cricketer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cricketer" asp-action="GetAllCricketer">Display</a>
                        </li>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CricketWebMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>